name: ci

on:
  push:
    branches: [main]
    paths: &ci_paths
      - include/**
      - src/**
      - tests/**
      - benchmarks/**
      - third_party/**
      - .github/workflows/ci.yml
      - xmake.lua
      - .clang-tidy
      - CPPLINT.cfg
      - uv.lock
  pull_request:
    branches: [main]
    paths: *ci_paths
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            plat: linux
            arch: x86_64
            stdlib: libc++
            sanitizers: y
            libunwind: y
          - os: windows-2025-vs2026
            plat: windows
            arch: x64
            stdlib: msvc
            sanitizers: n
            libunwind: n
          - os: macos-26
            plat: macosx
            arch: arm64
            stdlib: libc++
            sanitizers: n
            libunwind: n
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build and test (${{ matrix.os }})
    env:
      CC: clang
      CXX: clang++
      COLORTERM: 256color
      XMAKE_COLORTERM: 256color
      XMAKE_ROOT: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libc++-dev libc++abi-dev clang clang-format clang-tidy

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          # https://github.com/astral-sh/uv/tags
          version: 0.10.7
          enable-cache: true

      - name: Sync python dependencies with uv
        run: uv sync
        shell: bash

      - name: Setup mold
        if: runner.os == 'Linux'
        uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444
        with:
          mold-version: 2.41.0
          make-default: true

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a
        with:
          # https://github.com/xmake-io/xmake/tags
          xmake-version: 3.0.8
          actions-cache-folder: .xmake-cache
          actions-cache-key: ${{ matrix.os }}-${{ matrix.plat }}-${{ matrix.arch }}-xmake
          package-cache: true
          package-cache-key: ${{ matrix.os }}-${{ matrix.plat }}-${{ matrix.arch }}-packages
          build-cache: true
          build-cache-path: build/.build_cache
          build-cache-key: ${{ matrix.os }}-${{ matrix.plat }}-${{ matrix.arch }}-build
          project-path: .

      - name: Install LLVM tools
        uses: KyleMayes/install-llvm-action@ebc0426251bc40c7cd31162802432c68818ab8f0
        with:
          # https://github.com/KyleMayes/install-llvm-action/blob/master/assets.json
          version: 21.1.8

      - name: Setup environment variables
        shell: bash
        run: |
          if [[ "${{ matrix.plat }}" == "macosx" ]]; then
            xcode-select --install || true
            SDK=$(xcrun --show-sdk-path)
            echo "SDKROOT=$SDK" >> $GITHUB_ENV
            echo "LDFLAGS=-L$SDK/usr/lib" >> $GITHUB_ENV
            echo "CXXFLAGS=-isysroot $SDK" >> $GITHUB_ENV
          fi

      - name: Configure
        shell: bash
        run: |
          xmake config -c -y \
            -m debug \
            --tests=y \
            --benchmarks=y \
            --toolchain=llvm \
            --stdlib="${{ matrix.stdlib }}" \
            --sanitizers="${{ matrix.sanitizers }}" \
            --libunwind="${{ matrix.libunwind }}" \
            -p "${{ matrix.plat }}" \
            -a "${{ matrix.arch }}"

      - name: Build
        shell: bash
        run: |
          xmake build -w

      - name: Build tests and run
        shell: bash
        run: xmake run tests

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{ matrix.plat }}-${{ matrix.arch }}
          path: build/${{ matrix.plat }}/${{ matrix.arch }}/**

      - name: Analyze statically
        if: runner.os == 'Linux'
        shell: bash
        run: |
          xmake check api
          xmake check clang
          xmake lint
