name: ci

on:
  push:
    branches: [main]
    paths: &ci_paths
      - src/**
      - tests/**
      - benchmarks/**
      - third_party/**
      - .github/workflows/ci.yml
      - xmake.lua
      - .clang-tidy
      - CPPLINT.cfg
      - uv.lock
  pull_request:
    branches: [main]
    paths: *ci_paths
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            plat: linux
            arch: x86_64
            stdlib: libstdc++
            sanitizers: y
            libunwind: y
          - os: windows-2025-vs2026
            plat: windows
            arch: x64
            stdlib: msvc
            sanitizers: n
            libunwind: n
          - os: macos-26
            plat: macosx
            arch: arm64
            stdlib: libc++
            sanitizers: n
            libunwind: n
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build and test (${{ matrix.os }})
    env:
      CC: clang
      CXX: clang++
      XMAKE_COLORTERM: color256
    steps:
      - name: checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          # https://github.com/astral-sh/uv/tags
          version: "0.10.7"
          enable-cache: true

      - name: sync python dependencies with uv
        run: uv sync
        shell: bash

      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a
        with:
          # https://github.com/xmake-io/xmake/tags
          xmake-version: "3.0.8"
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: "${{ matrix.os }}-xmake"
          package-cache: true
          package-cache-key: "${{ matrix.os }}-packages"
          build-cache: true
          build-cache-path: "build/.build_cache"
          build-cache-key: "${{ matrix.os }}-build"
          project-path: "."

      - name: install llvm tools
        uses: KyleMayes/install-llvm-action@ebc0426251bc40c7cd31162802432c68818ab8f0
        with:
          # https://github.com/KyleMayes/install-llvm-action/blob/master/assets.json
          version: "21.1.8"

      - name: setup environment variables
        shell: bash
        run: |
          if [[ "${{ matrix.plat }}" == "macosx" ]]; then
            xcode-select --install || true
            SDK=$(xcrun --show-sdk-path)
            echo "SDKROOT=$SDK" >> $GITHUB_ENV
            echo "LDFLAGS=-L$SDK/usr/lib" >> $GITHUB_ENV
            echo "CXXFLAGS=-isysroot $SDK" >> $GITHUB_ENV
          fi

      - name: configure
        shell: bash
        run: |
          xmake config -c -y \
            -m debug \
            --tests=y \
            --benchmarks=y \
            --toolchain=llvm \
            --stdlib="${{ matrix.stdlib }}" \
            --sanitizers="${{ matrix.sanitizers }}" \
            --libunwind="${{ matrix.libunwind }}" \
            -p "${{ matrix.plat }}" \
            -a "${{ matrix.arch }}"

      - name: build
        shell: bash
        run: xmake build -w

      - name: build tests and run
        shell: bash
        run: xmake run tests

      - name: upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: "${{ matrix.os }}"
          path: out/*

      - name: analyze statically
        if: matrix.os == 'ubuntu-24.04'
        shell: bash
        run: |
          # needs toolchain("llvm")
          # runs clang-tidy
          # runs uv run cpplint

          xmake check api
          xmake check clang
          xmake lint
