name: Spell checks

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell check with typos
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        submodules: recursive

    - name: Spell check repository
      uses: crate-ci/typos@2a44449ff3410624a0fa2ea073c670e1c9236a40

